global:
  scrape_interval: 10s

scrape_configs:
  # --- Tomato API ---
  - job_name: "tomato_api"
    static_configs:
      - targets: ["tomato-api-service:80"] # K8s Service Name

  # --- Pushgateway (For Workers) ---
  - job_name: "tomato_pushgateway"
    honor_labels: true  
    static_configs:
      - targets: ["pushgateway-service:9091"]

  # --- Redis Exporter ---
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter-service:9121"]

  # --- Prometheus Self ---
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]