apiVersion: v1
kind: Service
metadata:
  name: tomato-api-service
  labels:
    app: tomato-api
spec:
  #  Headless Service ---
  # clusterIP: None allows Nginx to perform true 'least_conn' balancing 
  # by seeing the individual IP of every scaled FastAPI pod.
  clusterIP: None 
  selector:
    app: tomato-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000