# --- 1. API FIREWALL: Only Nginx can talk to the API ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-api
spec:
  podSelector:
    matchLabels:
      app: tomato-api
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
---
# --- 2. REDIS FIREWALL: Only API and Worker can talk to Redis ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-redis
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: tomato-api
    - podSelector:
        matchLabels:
          app: tomato-worker
---
# --- 3. DATABASE FIREWALL: Only Worker and MLflow can talk to Postgres ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-to-db
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: tomato-worker
    - podSelector:
        matchLabels:
          app: mlflow
---
# --- 4. MONITORING FIREWALL: Allow Prometheus to scrape everyone ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scraping
spec:
  podSelector: {} # Applies to all pods in the namespace
  policyTypes: [Ingress]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: monitoring