apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tomato-api
  template:
    metadata:
      labels:
        app: tomato-api
    spec:
      imagePullSecrets: [{name: github-auth}]
      
      # --- SENIOR SECURITY CONTEXT (Pod Level) ---
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000

      containers:
      - name: tomato-api
        image: ghcr.io/arindamdas07/tomato-mlops-platform-api:latest
        
        # --- SENIOR SECURITY CONTEXT (Container Level) ---
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true  # The 'Iron Cage'
          runAsUser: 1000

        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits: { cpu: "500m", memory: "512Mi" }

        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 15

        envFrom:
        - configMapRef: { name: tomato-config }
        - secretRef: { name: tomato-secrets }
            
        volumeMounts:
        - name: shared-uploads
          mountPath: /app/uploads
        # Exception for ReadOnlyRootFilesystem: Allow writing to /tmp
        - name: tmp-volume
          mountPath: /tmp
      
      volumes:
      - name: shared-uploads
        persistentVolumeClaim: { claimName: tomato-upload-pvc }
      - name: tmp-volume
        emptyDir: {}