apiVersion: v1
kind: ConfigMap
metadata:
  name: tomato-config
  labels:
    app: tomato-mlops
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres"
  
  REDIS_DB_TASKS: "0"
  REDIS_DB_RESULTS: "1"
  REDIS_DB_APP: "2"
  
  MLFLOW_URI: "http://mlflow:5000"
  # THE FIX: Points to the service name we defined in monitoring-stack
  PUSHGATEWAY: "http://pushgateway-service:9091"
  
  RESULT_TTL: "3600" 
  ALLOWED_ORIGINS: "*" 
  UPLOAD_DIR: "/app/uploads"
  ENV: "production"