apiVersion: batch/v1
kind: CronJob
metadata:
  name: tomato-janitor
spec:
  # Schedule: Runs every hour, on the hour.
  schedule: "0 * * * *"
  
  # Clean up old metadata from the Kubernetes dashboard
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  
  # Prevent multiple janitors from running if one gets stuck
  concurrencyPolicy: Forbid 

  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets: [{name: github-auth}]
          containers:
          - name: janitor
            image: ghcr.io/arindamdas07/tomato-mlops-platform-worker:latest
            command: ["python", "worker/janitor.py"]
            
            # --- SENIOR OPTIMIZATION ---
            # We use very low requests so the scheduler can 'squeeze' 
            # this pod into your laptop's remaining RAM/CPU.
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
              limits:
                cpu: "100m"
                memory: "128Mi"

            volumeMounts:
            - name: image-storage
              mountPath: /app/uploads
              # subPath REMOVED: We mount the whole dedicated Upload PVC
              
          restartPolicy: OnFailure
          volumes:
          - name: image-storage
            persistentVolumeClaim: 
              # --- THE CRITICAL FIX ---
              # Must match the new name from your upload-pvc.yaml
              claimName: tomato-upload-pvc