apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato-worker
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: tomato-worker
  template:
    metadata:
      labels:
        app: tomato-worker
    spec:
      imagePullSecrets: [{name: github-auth}]
      
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000

      containers:
      - name: tomato-worker
        image: ghcr.io/arindamdas07/tomato-mlops-platform-worker:latest
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 1000

        resources:
          requests: { memory: "1Gi", cpu: "500m" }
          limits: { memory: "3Gi", cpu: "1000m" }
            
        envFrom:
        - configMapRef: { name: tomato-config }
        - secretRef: { name: tomato-secrets }

        livenessProbe:
          exec: { command: ["pgrep", "-f", "celery"] }
          initialDelaySeconds: 30 

        volumeMounts:
        - name: shared-uploads
          mountPath: /app/uploads
        - name: tmp-volume
          mountPath: /tmp
      
      volumes:
      - name: shared-uploads
        persistentVolumeClaim: { claimName: tomato-upload-pvc }
      - name: tmp-volume
        emptyDir: {}