apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomato-api
  template:
    metadata:
      labels:
        app: tomato-api
    spec:
      imagePullSecrets: [{name: github-auth}]
      containers:
      - name: tomato-api
        image: ghcr.io/arindamdas07/tomato-mlops-platform-api:latest
        resources: # Added for HPA compatibility
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom: [{configMapRef: {name: tomato-config}}]
        volumeMounts:
        - name: shared-storage
          mountPath: /app/uploads
          subPath: active-sessions
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: tomato-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tomato-api-service
spec:
  # --- THE ELITE FIX: Headless Service ---
  # This allows Nginx to see individual Pod IPs for true Least-Conn
  clusterIP: None 
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: tomato-api