apiVersion: v1
kind: ConfigMap
metadata:
  name: tomato-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB_TASKS: "0"
  REDIS_DB_RESULTS: "1"
  REDIS_DB_APP: "2"
  MLFLOW_URI: "http://mlflow:5000"
  PUSHGATEWAY: "http://pushgateway-service:9091"