apiVersion: batch/v1
kind: CronJob
metadata:
  name: tomato-janitor
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets: [{name: github-auth}]
          containers:
          - name: janitor
            image: ghcr.io/arindamdas07/tomato-mlops-platform-worker:latest
            command: ["python", "worker/janitor.py"]
            volumeMounts:
            - name: shared-storage
              mountPath: /app/uploads
              subPath: active-sessions # ONLY CLEAN THIS
          restartPolicy: OnFailure
          volumes:
          - name: shared-storage
            persistentVolumeClaim: {claimName: tomato-pvc}