apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
        server {
            listen 80;
            client_max_body_size 10M; # For high-res leaf photos
            location / {
                limit_req zone=api_limit burst=10 nodelay;
                proxy_pass http://tomato-api-service:80;
                proxy_set_header Host $host;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: conf
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: LoadBalancer # This is your MAIN ENTRY POINT
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx