name: Build and Push Production Images

on:
  push:
    branches: [ "main" ]

# --- NEW: Explicitly grant permission to write to packages ---
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # GitHub package names MUST be lowercase
  IMAGE_NAME_API: tomato-mlops-platform-api
  IMAGE_NAME_WORKER: tomato-mlops-platform-worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Pulls your ResNet model

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: . # This tells Docker the root folder is the starting point
          file: ./api/Dockerfile.api
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_API }}:latest

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: . # This tells Docker the root folder is the starting point
          file: ./worker/Dockerfile.worker
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_WORKER }}:latest